import Head from 'next/head'
import Image from 'next/image'
import Contents from '../components/start_page/Contents'
import Header from '../components/start_page/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

      <Header />

      <Contents />

      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trests</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>
      <p>trest</p>
      <br></br>

    </div>
  )
}
